### ISSUE TITLE
"Company is looking for" section

### ISSUE THREAD

**Issue by jazzjacob** [Systemvetardagen/systemvetardagen.se#243]
See figma file "Company page wireframe" or talk to jacob for more info

- Getting specific colors is not important right now - will decide this later

![Image](https://github.com/Systemvetardagen/systemvetardagen.se/assets/80760206/8036664c-4016-4680-858d-6d2b25dffeaa)

**Comment by olehoef** [comment]
Design is finished. I used the Systemvetardagen theme colors.

![image](https://github.com/Systemvetardagen/systemvetardagen.se/assets/81076759/5975935e-7812-4a81-9a41-c0f9d596615e)

The only thing that's left are the master programs. The question is how to access them best. Rn all programs are combined. Maybe we could use the master boolean from the CMS to filter them in the front end instead of getting them separately from the CMS @ ? Let's discuss on Friday.

**Comment by olehoef** [comment]
Waiting for issue #259 ...
