### ISSUE TITLE
About us - Project group presentation

### ISSUE THREAD

**Issue by jazzjacob** [Systemvetardagen/systemvetardagen.se#263]
See image or figma file "about page".

Size and scales are approximate, so use your own taste and creativity to get it feel "right" on different window sizes

![Image](https://github.com/Systemvetardagen/systemvetardagen.se/assets/80760206/74901b4d-5514-479c-9b21-6ec04398bc85)

**Comment by olehoef** [comment]
<img width="1251" alt="Screenshot 2024-01-19 at 11 26 27" src="https://github.com/Systemvetardagen/systemvetardagen.se/assets/81076759/b4d25a96-7f83-4bf1-bd3a-b6544369a1e7">
<img width="1213" alt="Screenshot 2024-01-19 at 11 26 40" src="https://github.com/Systemvetardagen/systemvetardagen.se/assets/81076759/dd950ae7-7cb9-4d42-a0c6-03cb7d753009">
<img width="337" alt="Screenshot 2024-01-19 at 11 27 35" src="https://github.com/Systemvetardagen/systemvetardagen.se/assets/81076759/a4951dee-b3f9-432c-9fc8-8eb93fc55163">


@jazzjacob what do you think? I thought it was better to have the team members expandable since we have quite a few people to cover this year. Otherwise my fear is that the about page gets super crowded.

**Comment by jazzjacob** [comment]
@olehoef I'd say it's easier to scroll through it all than having to press mutiple dropdowns. And will it really be _that_ many names?

But my opinion isn't that strong (since this component is not essential to the site), so do your way if you still feel like it!!

**Comment by olehoef** [comment]
I see your point. Let's think about this for a bit longer. 

But I like the division per team. I think it gives the page more structure. My idea was that team heads and vices are more dominantly featured then. 

As fo for the no of people, we have 5 (if I'm counting right)  teams à 2 managers and at least 5 members each. So...35 + PM.
