### ISSUE TITLE
Company page overflow below ~400px width

### ISSUE THREAD

**Issue by jazzjacob** [Systemvetardagen/systemvetardagen.se#316]
The comapny page slightly extend beyond screen width, when screen width is below around 400px (don't know exact breakpoint for this problem).

I have this issue on safari on my iPhone 12 mini, and can replicate it in my desktop browsers.

The page should never overflow, or at least work perfectly down to around 300px width.

**Example:**
<img width="335" alt="Screenshot 2024-02-09 at 10 30 07" src="https://github.com/Systemvetardagen/systemvetardagen.se/assets/80760206/9c578268-56dc-4e62-aaa4-d79a7989cf90">

**Comment by amirhossein-haerian** [comment]
<img width="1440" alt="Screenshot 2024-02-09 at 11 30 10" src="https://github.com/Systemvetardagen/systemvetardagen.se/assets/44199492/63dec073-b2c2-4b0b-bc54-9cd7b5c07c57">
Here I have used 400px as min-width, one possible solution than can fix the problem is to to change 400 px to 40vw. 

I should consider this 🙌

**Comment by jazzjacob** [comment]
I am working on it now, and yes that is one of the problems! But not the only one. I think I have located all problem so it will be fixed
